# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 734)
        MainWindow.setStyleSheet("#side_widget QPushButton{\n"
"text-align:left;\n"
"background:transparent;\n"
"}\n"
"\n"
"#menu_frame QPushButton{\n"
"color:#fff;\n"
"border:none;\n"
"padding:5px 10px;\n"
"border-radius:5px;\n"
"background:none;\n"
"}\n"
"#menu_frame QFrame{\n"
"border-radius:5px;\n"
"}\n"
"#menu_frame{\n"
"border-top:.5px solid #4d4d4f;\n"
"}\n"
"#new_chat_btn{\n"
"border:1px solid #4d4d4f;\n"
"color:#fff;\n"
"border-radius:5px;\n"
"padding:10px;\n"
"}\n"
"\n"
"#side_widget,\n"
"#chat_list{\n"
"background:#202123;\n"
"}\n"
"\n"
"#chat_list{\n"
"border:none;\n"
"}\n"
"#side_widget QPushButton:hover,\n"
"#chat_list::itemhover,\n"
"#user_frame:hover,\n"
"#menu_frame QFrame:hover{\n"
"background:#2a2b32;\n"
"/*cursor:pointer;*/\n"
"}\n"
"#chat_list::item{\n"
"    color:#fff;\n"
"    padding:10px;\n"
"    border-radius:5px;\n"
"    margin-top:5px;\n"
"}\n"
"\n"
"#new_label{\n"
"padding:5px;\n"
"border-radius:6px;\n"
"background-color:#fae69e;\n"
"}\n"
"\n"
"#comboBox{\n"
"border:none;\n"
"/*background:#202123;*/\n"
"background:transparent;\n"
"color:#fff;\n"
"padding:0px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"#input_frame{\n"
"    border: 1px solid #e5e5e5;\n"
"background:#fff;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#input_textEdit{\n"
"    border:none;\n"
"\n"
"}\n"
"\n"
"#send_btn{\n"
"    border:none;\n"
"padding:5px;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#send_btn:hover{\n"
"    background:#ececf;\n"
"}\n"
"#main_scrollArea {\n"
"    border:none;\n"
"}\n"
" #main_widget ,#scrollArea{\n"
"    border:#fff;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.side_widget = QtWidgets.QWidget(self.centralwidget)
        self.side_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget.setObjectName("side_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.new_chat_frame = QtWidgets.QFrame(self.side_widget)
        self.new_chat_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_chat_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_chat_frame.setObjectName("new_chat_frame")
        self.new_chat_btn = QtWidgets.QPushButton(self.new_chat_frame)
        self.new_chat_btn.setGeometry(QtCore.QRect(30, 10, 151, 42))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.new_chat_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add_google_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_chat_btn.setIcon(icon)
        self.new_chat_btn.setIconSize(QtCore.QSize(18, 18))
        self.new_chat_btn.setObjectName("new_chat_btn")
        self.verticalLayout_2.addWidget(self.new_chat_frame)
        self.chat_list_frame = QtWidgets.QFrame(self.side_widget)
        self.chat_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_list_frame.setObjectName("chat_list_frame")
        self.chat_list = QtWidgets.QListWidget(self.chat_list_frame)
        self.chat_list.setGeometry(QtCore.QRect(30, 10, 181, 261))
        self.chat_list.setObjectName("chat_list")
        self.verticalLayout_2.addWidget(self.chat_list_frame)
        self.menu_frame = QtWidgets.QFrame(self.side_widget)
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.menu_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(18, 18))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.menu_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(18, 18))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/user.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.new_label = QtWidgets.QLabel(self.frame_7)
        self.new_label.setGeometry(QtCore.QRect(0, 10, 35, 20))
        self.new_label.setMaximumSize(QtCore.QSize(45, 20))
        self.new_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_label.setObjectName("new_label")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 10, 111, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.menu_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMaximumSize(QtCore.QSize(18, 18))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/robot.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setEnabled(False)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 42))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.menu_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setMaximumSize(QtCore.QSize(18, 18))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/icons/dark.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.menu_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(18, 18))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/update.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.menu_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setMaximumSize(QtCore.QSize(18, 18))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icons/icons/logout.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.menu_frame)
        self.horizontalLayout_8.addWidget(self.side_widget)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setEnabled(True)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.input_frame = QtWidgets.QFrame(self.main_widget)
        self.input_frame.setMaximumSize(QtCore.QSize(561, 68))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout.setContentsMargins(10, 10, 5, 10)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout.addWidget(self.input_textEdit, 0, 0, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.input_frame)
        self.send_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_btn.setIcon(icon1)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.input_frame, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 792, 620))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(20, 599, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.horizontalLayout_8.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_chat_btn.setText(_translate("MainWindow", "New Chat"))
        self.pushButton.setText(_translate("MainWindow", "Clear Conversations"))
        self.pushButton_2.setText(_translate("MainWindow", "Update to Plus"))
        self.new_label.setText(_translate("MainWindow", "NEW"))
        self.pushButton_7.setText(_translate("MainWindow", "Clear Conversations"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ChatGPT"))
        self.pushButton_4.setText(_translate("MainWindow", "Dark Mode"))
        self.pushButton_5.setText(_translate("MainWindow", "Updates & FAQ"))
        self.pushButton_6.setText(_translate("MainWindow", "Log Out"))
from static import resource_rc
